name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v5.0.0
          
    - name: Build and Package
      run: |
          cd spring-boot-app
          mvn clean package
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd spring-boot-app && docker build . --tag my-image-name:$(date +%s)
